---
title: PICA Normalized
---

PICA Normalized is the preferred machine-readable serialization of PICA records (although not widely used by OCLC CBS/LBS). Each record is stored on a line. PICA fields end with byte code `#x1E` and subfields start with byte code `#x1F`.

::: {.callout-tip}
Other PICA serialization formats are also referred to as "normalized" so the URI of PICA Normalized should be used for reference.
A common file extension for PICA Normalized is `.dat`.
:::

## Specification {.unnumbered}

The URI of PICA Normalized is <https://format.gbv.de/pica/normalized>.

**Collection**, **record**, **field**, **field identifier**, **subfields**, **subfield code** and **subfield value** are defined by the [PICA Data Model](pica-model.qmd).

A **collection** is encoded as sequence of encoded **records**, separated by a line feed (`#x0A`). The last **record** MAY be terminated by an additional newline character (`#x0A`). A **record** is encoded as sequence of **fields**, each encoded as sequence of:

1. the **field identifier**
2. a space (`#x20`)
3. the list of **subfields**, each the subfield indicator `#x1F` followed by the **subfield code** followed by the **subfield value**
4. the byte `#x1E`

